### ISSUE TITLE
Issue Routing on K5 after terraform applying

### ISSUE THREAD

**Issue by geofffranks** [allthingsclowd/K5_Terraform_Deployment_Example#1]
Hey, thanks repo + your blog post about it! Super helpful when trying to spin up a new environment on K5. However, I'm running into a weird issue with my routers, and as far as I can tell, I'm doing the same thing you have on github.

When we create a new environment with terraform, our server with a floating IP is inaccessible, until we manually issue a `PUT /v2/routers/<router_id>` with the body `{"routers":{"external_gateway_info":{"network_id":"<network_id>"}}}`. The network ID is present before + after we do the PUT request, but after making it, things  start working.

I've taken a look at before/after API output of `/v2.0/routers`, `/v2.0/networks`, `/v2.0/ports`, and `/v2.0/subnets`. Nothing's changed according to the API, but yet somehow it was necessary to make things work. Ever run into that before?

I'm also curious about the `update_gateway_info = true` line (https://github.com/allthingsclowd/K5_Terraform_Deployment_Example/blob/master/k5-1a.tf#L36), since it's commented out. Makes me wonder if i need it or something like it, but it's not present in the TF docs, so maybe it needs to be in value_specs?

**Comment by geofffranks** [comment]
Seems like this is related to K5 not allowing you to specify the `external_gateway_info` data when creating a new router (must be done in two steps).. So create router without external gateway, then update router with external gateway + associate the FIP to the VM

**Comment by allthingsclowd** [comment]
Yes, unfortunately it's a documented feature that I was hoping would be fixed on K5. Should work with native OpenStack though.
